### PR TITLE
fix(React): Use componentDidMount instead of componentWillMount

### PR DESCRIPTION
**Pull request by koba04**
React is going to deprecate `componentWillMount` so Almin should use `componentDidMount` instead of `componentWillMount`.
This PR includes fixes for documentation and an example and a source of `almin-react-container`.

Should I separate this PR each one?

### CODE REVIEW

**Comment by azu** [comment]
> Should I separate this PR each one?

Almin project use [Conventional Commits](https://conventionalcommits.org/ "Conventional Commits").

- https://github.com/almin/almin/blob/master/.github/CONTRIBUTING.md#how-to-write-git-commit-message

If the scope is difference, you should separate commits.
In this case, separate commits into `counter` and `almin-react-container`.

Can you separate the commit into follows?

- `fix(counter): Use componentDidMount instead of componentWillMount`
- `fix(almin-react-container): Use componentDidMount instead of componentWillMount`

Actually, lerna use this commit message for generating CHANGELOG and versioning.

- [lerna publish --conventional-commits](https://github.com/lerna/lerna#--conventional-commits "-conventional-commits")

**Comment by azu** [comment]
> Should I separate this PR each one?

A single PR includes multiple commits is OK.

**Comment by azu** [comment]
FYI: I've update commit message style document #322

**Comment by koba04** [comment]
@azu Thank you for your help! I've fixed it.

**Comment by azu** [comment]
Thanks!

**Comment by koba04** [comment]
Thank you!

**Pull request merged**
